name: CreateFramework

on:
  push:
    branches: 
    - master
    
jobs:
  build:
    name: Build iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild archive \
          -scheme FrameworkActionsDemo \
          -configuration Release \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath './iOS_Framework_Actions' \
          SKIP_INSTALL=NO \
          BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
