name: CreateFramework

on:
  push:
    branches: 
    - master
    
jobs:
  build:
    name: Build iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create a file
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" > a.txt
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Added framework"
          git push
