name: CreateFramework

on:
  push:
    branches: 
    - master
    
jobs:
  build:
    name: Build iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        run: |
          xcodebuild archive \
          -scheme FrameworkActionsDemo \
          -configuration Release \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath './iOS_Framework_Actions' \
          SKIP_INSTALL=NO \
          BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
